apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx-dep
   labels:
      app: myapp
      env: dev
spec:
   replicas: 4
   selector:
      matchLabels:
         app: myapp
   template:
      metadata:
         labels:
            app: myapp
      spec:
         containers:
         - name: nginx
           image: devpipeline/ravi:{{ .Values.image.tag }}
